#esta es la version estable a utilizar 14 Agosto 2021
# docker network create --gateway 172.20.0.1 --subnet 172.20.0.0/16 microred
#
version: '3'

services:
  gate:
    container_name: micro-gate
    hostname: gate
    image: jhipster/jhipster:v6.8.0
    restart: always
    volumes:
      - ~/jhipster/proyecto/microservicio/gate:/home/jhipster/app/gate
      - ~/jhipster/proyecto/microservicio/gate/.m2:/home/jhipster/.m2
    ports:
      - "8080:8080"
#      - "9000:9000"
#      - "3001:3001"
#    environment:
#      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    working_dir: /home/jhipster/app/gate
#    command: bash -c "./mvnw -Pprod clean verify -DskipTests && java -jar target/gate.jar --server.servlet.context-path=/gate/"
    networks:
      net-micro:
        ipv4_address: 172.20.0.2

  micro:
    container_name: micro-back
    hostname: micro
    image: jhipster/jhipster:v6.8.0
    restart: always
    volumes:
      - ~/jhipster/proyecto/microservicio/micro:/home/jhipster/app/micro
      - ~/jhipster/proyecto/microservicio/micro/.m2:/home/jhipster/.m2
    ports:
      - "8082:8080"
#      - "9000:9000"
#      - "3001:3001"
#    environment:
#      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    working_dir: /home/jhipster/app/micro
#    command: bash -c "./mvnw -Pprod clean verify -DskipTests && java -jar target/micro.jar --server.servlet.context-path=/micro/"
    networks:
      net-micro:
        ipv4_address: 172.20.0.4

  micro-mariadb:
    container_name: micro-mariadb
    hostname: micro-mariadb
    image: mariadb:10.5.3
    restart: always    
    volumes:
      - ~/data/micro/mysql/:/var/lib/mysql/
      - ~/data/micro/backup/:/home/data/backup/
    environment:
      - MYSQL_ROOT_PASSWORD=developer
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_DATABASE=micro
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      net-micro:
        ipv4_address: 172.20.0.6          

  consul:
    container_name: micro-consul
    hostname: consul
    restart: always    
    image: consul:1.7.1
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0
    networks:
      net-micro:
        ipv4_address: 172.20.0.8
        
  consul-config-loader:
    image: jhipster/consul-config-loader:v0.3.0
    container_name: micro-loader-consul
    hostname: micro-loader-consul
    restart: always
    volumes:
      - ~/jhipster/proyecto/microservicio/central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
    # Uncomment to load configuration into Consul from a Git repository
    # as configured in central-server-config/git2consul.json
    # Also set SPRING_CLOUD_CONSUL_CONFIG_FORMAT=files on your apps
    # - CONFIG_MODE=git
    networks:
      net-micro:
        ipv4_address: 172.20.0.10
      
networks:
  net-micro:
    external:
      name: microred

