version: '2'
services:
  micro-mariadb:
    container_name: micro-mariadb
    image: mariadb:10.4.12
    volumes:
      - ~/data/micro/mysql/:/var/lib/mysql/
      - ~/data/micro/backup/:/home/data/backup/
    environment:
      - MYSQL_ROOT_PASSWORD=developer
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_DATABASE=micro
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
